include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/GoogleBenchmark.cmake")
set(APPLE TRUE)
foreach(compiler IN ITEMS AppleClang Clang GNU)
  set(CMAKE_CXX_COMPILER_ID "${compiler}")
  modern_leveldb_profile_markers(supported)
  if(compiler STREQUAL "AppleClang")
    if(NOT supported EQUAL 1)
      message(FATAL_ERROR "AppleClang on macOS must support capture")
    endif()
  elseif(NOT supported EQUAL 0)
    message(FATAL_ERROR "Non-Apple compiler ${compiler} was accepted for capture")
  endif()
endforeach()
set(APPLE FALSE)
set(CMAKE_CXX_COMPILER_ID AppleClang)
modern_leveldb_profile_markers(supported)
if(NOT supported EQUAL 0)
  message(FATAL_ERROR "Capture requires macOS")
endif()
if(MODERN_LEVELDB_WINDOWS_PROFILE_CAPTURE)
  message(FATAL_ERROR "Windows collector was enabled without its admitted backend")
endif()
set(MODERN_LEVELDB_HAVE_WINDOWS_FILE_SYSTEM TRUE)
set(CMAKE_CXX_COMPILER_ID MSVC)
modern_leveldb_profile_markers(supported)
if(NOT supported EQUAL 0 OR NOT MODERN_LEVELDB_WINDOWS_PROFILE_CAPTURE EQUAL 1)
  message(FATAL_ERROR "Native Windows must use its owned collector, not macOS markers")
endif()
