include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/GoogleBenchmark.cmake")
set(APPLE TRUE)
foreach(compiler IN ITEMS AppleClang Clang GNU)
  set(CMAKE_CXX_COMPILER_ID "${compiler}")
  modern_leveldb_profile_markers(supported)
  if(compiler STREQUAL "AppleClang")
    if(NOT supported EQUAL 1)
      message(FATAL_ERROR "AppleClang on macOS must support capture")
    endif()
  elseif(NOT supported EQUAL 0)
    message(FATAL_ERROR "Non-Apple compiler ${compiler} was accepted for capture")
  endif()
endforeach()
set(APPLE FALSE)
set(CMAKE_CXX_COMPILER_ID AppleClang)
modern_leveldb_profile_markers(supported)
if(NOT supported EQUAL 0)
  message(FATAL_ERROR "Capture requires macOS")
endif()
