function(modern_leveldb_crc32c_dependency output)
  set(revision "2bbb3be42e20a0e6c0f7b39dc07dc863d9ffbc07")
  set(source "")
  set(provider "")
  set(arm64 "external")
  set(sse42 "external")
  if(TARGET Crc32c::crc32c)
    set(selected Crc32c::crc32c)
    set(provider "parent-target")
  elseif(TARGET crc32c)
    set(selected crc32c)
    set(provider "parent-target")
  else()
    include(FetchContent)
    get_property(declared GLOBAL PROPERTY _FetchContent_modern_leveldb_crc32c_savedDetails DEFINED)
    if(declared)
      message(FATAL_ERROR "Modern LevelDB rejects a predeclared private CRC32C dependency")
    endif()
    foreach(option IN ITEMS CRC32C_BUILD_TESTS CRC32C_BUILD_BENCHMARKS CRC32C_USE_GLOG CRC32C_INSTALL)
      if(NOT DEFINED "${option}")
        set("${option}" OFF)
      endif()
    endforeach()
    # Keep the fetched dependency static without changing the parent's cache setting.
    set(BUILD_SHARED_LIBS OFF)
    FetchContent_Declare(
      modern_leveldb_crc32c
      URL "https://github.com/google/crc32c/archive/${revision}.tar.gz"
      DOWNLOAD_EXTRACT_TIMESTAMP TRUE
      SYSTEM
    )
    FetchContent_MakeAvailable(modern_leveldb_crc32c)
    set_property(DIRECTORY "${modern_leveldb_crc32c_SOURCE_DIR}" PROPERTY EXCLUDE_FROM_ALL TRUE)
    if(NOT TARGET crc32c)
      message(FATAL_ERROR "The CRC32C source did not define target crc32c")
    endif()
    set(selected crc32c)
    set(source "${modern_leveldb_crc32c_SOURCE_DIR}")
    set(provider "pinned-source")
    if(FETCHCONTENT_SOURCE_DIR_MODERN_LEVELDB_CRC32C)
      set(provider "source-override")
    endif()
    set(arm64 "false")
    set(sse42 "false")
    if(HAVE_ARM64_CRC32C)
      set(arm64 "true")
    endif()
    if(HAVE_SSE42)
      set(sse42 "true")
    endif()
  endif()
  set("${output}" "${selected}" PARENT_SCOPE)
  set(MODERN_LEVELDB_CRC32C_REQUESTED_REVISION "${revision}" PARENT_SCOPE)
  set(MODERN_LEVELDB_CRC32C_PROVIDER "${provider}" PARENT_SCOPE)
  set(MODERN_LEVELDB_CRC32C_SOURCE_DIR "${source}" PARENT_SCOPE)
  set(MODERN_LEVELDB_CRC32C_COMPILED_ARM64 "${arm64}" PARENT_SCOPE)
  set(MODERN_LEVELDB_CRC32C_COMPILED_SSE42 "${sse42}" PARENT_SCOPE)
endfunction()
